apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: khup/webui-auth_backend:v1
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_HOST
              value: mysqldb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: coinminer
            - name: MYSQL_ROOT_PASSWORD
              value: my-secret-pw
            - name: MYSQL_PORT
              value: "3306"
