apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
        - name: hasher
          image: khup/webui-auth_hasher:v1
          ports:
            - name: http-port
              containerPort: 80
