apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
        - name: rng
          image: khup/webui-auth_worker:v1
          ports:
            - name: http-port
              containerPort: 80
